spring:
  messages:
    basename: messages/messages
    encoding: UTF-8
  application:
    name:
      task-api-service

---

spring:
  profiles: container
  application:
    name: task-api-service
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  messages:
   basename: messages/messages
   encoding: UTF-8
server:
    port: ${API_PORT}
eureka:
    instance:
      ip-address: ${EUREKA_HOSTNAME}
      prefer-ip-address: true
      status-page-url-path: /actuator/info
    client:
      serviceUrl:
        defaultZone:
          http://${EUREKA_HOSTNAME}:8761/eureka


