spring:
  messages:
    basename: messages/messages
    encoding: UTF-8

---

spring:
  profiles: container
  application:
    name: task-api-service
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  messages:
   basename: messages/messages
   encoding: UTF-8
server:
    port: ${API_PORT}

